### ISSUE TITLE
sparql-contrastive data not in HF

### ISSUE THREAD

**Issue by jcrangel** [DAMO-NLP-SG/chain-of-knowledge#1]
Great job on the project!

I attempted to execute the `sparql_contrast.sh` , but it appears that the dataset `veggiebird/sparql-contrastive`  is missing from HF. 

Thank you!

**Comment by xingxuanli** [comment]
Thank you for your interest in our work. The [dataset](https://huggingface.co/datasets/veggiebird/sparql-contrastive) should be available now.
