### ISSUE TITLE
error in “python run.py”

### ISSUE THREAD

**Issue by zhurui1995** [DAMO-NLP-SG/chain-of-knowledge#2]
File "/XXX/CoK/utils/hotpotqa_parser.py", line 89, in update_rationales_step_by_step
    domains = data_point["s1_domains"]
KeyError: 's1_domains'

Where is data_point["s1_domains"] assigned a value

**Comment by xingxuanli** [comment]
We have fixed the bug [here](https://github.com/DAMO-NLP-SG/chain-of-knowledge/commit/018ad7b9b87b654bbe2e10309c3c4d79b52b5106).
